# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    both_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - ARM-L-J1_Joint
      - ARM-L-J2_Joint
      - ARM-L-J3_Joint
      - ARM-L-J4_Joint
      - ARM-L-J5_Joint
      - ARM-L-J6_Joint
      - ARM-L-J7_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - ARM-R-J1_Joint
      - ARM-R-J2_Joint
      - ARM-R-J3_Joint
      - ARM-R-J4_Joint
      - ARM-R-J5_Joint
      - ARM-R-J6_Joint
      - ARM-R-J7_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
both_arm_controller:
  ros__parameters:
    joints:
      - ARM-L-J1_Joint
      - ARM-L-J2_Joint
      - ARM-L-J3_Joint
      - ARM-L-J4_Joint
      - ARM-L-J5_Joint
      - ARM-L-J6_Joint
      - ARM-L-J7_Joint
      - ARM-R-J1_Joint
      - ARM-R-J2_Joint
      - ARM-R-J3_Joint
      - ARM-R-J4_Joint
      - ARM-R-J5_Joint
      - ARM-R-J6_Joint
      - ARM-R-J7_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity